name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs Every Day

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: 'godnik' # Hashnode Username\
          COUNT: 2 #MAX Visisble
          STYLE: "blog-left"
          BLOG_URL: 'https://blackslate.io/author/nikhil-mishra' # Blog URL
          
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
